OpenWeather_API_KEY = '885cc30c15c4aa8545d655750bce81ab'
price_prognosis_csvpath = r'final_project\data\predicted_prices_withzones.csv'
electicity_generation_by_source_csvpath = r'final_project\data\Electricity generation by source - Sweden.csv'
tilt_and_direction_table_csvpath = r'final_project\data\tilt_and_direction_table.csv'
predicted_prices_withzones_csvpath = r'final_project\data\predicted_prices_withzones.csv'
